// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFvmNWtqNLtnxgJ6F-j63pFDYH6QglZ5k',
    appId: '1:702937350118:web:1cdcb49a9a567c986aa027',
    messagingSenderId: '702937350118',
    projectId: 'back-end-app-01-19792',
    authDomain: 'back-end-app-01-19792.firebaseapp.com',
    storageBucket: 'back-end-app-01-19792.appspot.com',
    measurementId: 'G-WNM84LVYD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZox5HaQZ6pbMlHoiQj0j99A_pzRkbBXw',
    appId: '1:702937350118:android:2a80f4ac524084bd6aa027',
    messagingSenderId: '702937350118',
    projectId: 'back-end-app-01-19792',
    storageBucket: 'back-end-app-01-19792.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSohyc4wG7_9AuZh_-iN3IoJ6VRUDHuTU',
    appId: '1:702937350118:ios:cc7c3f64f610b1a06aa027',
    messagingSenderId: '702937350118',
    projectId: 'back-end-app-01-19792',
    storageBucket: 'back-end-app-01-19792.appspot.com',
    iosBundleId: 'com.example.backendApp01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSohyc4wG7_9AuZh_-iN3IoJ6VRUDHuTU',
    appId: '1:702937350118:ios:08d98bd1698fa8bc6aa027',
    messagingSenderId: '702937350118',
    projectId: 'back-end-app-01-19792',
    storageBucket: 'back-end-app-01-19792.appspot.com',
    iosBundleId: 'com.example.backendApp01.RunnerTests',
  );
}
